/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_appsync_graphqlEndpoint": "https://zautc4mdljcmlcm6t43tsopno4.appsync-api.eu-north-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-north-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-zfsi53bi2nh45odcx46he3ykba",
    "aws_cognito_identity_pool_id": "eu-north-1:0ef6776b-18e8-43f0-ac8b-f45fa7e844b9",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_opjw6jxBa",
    "aws_user_pools_web_client_id": "4b51vgcu7u75kejadv9tje49ui",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "resumeinsightd4bc960853764939bda3ab68cd6f17cf111503-staging",
    "aws_user_files_s3_bucket_region": "eu-north-1"
};


export default awsmobile;
